//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fVis.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fVis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přidat....
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chyba při stanovování intervalu pro uložení..
        /// </summary>
        internal static string CannotDetermineInterval {
            get {
                return ResourceManager.GetString("CannotDetermineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Musíte vybrat alespoň dvě matematické funkce..
        /// </summary>
        internal static string ChooseAtLeastTwoFunctions {
            get {
                return ResourceManager.GetString("ChooseAtLeastTwoFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Soubor s uloženými hodnotami.
        /// </summary>
        internal static string DataSet {
            get {
                return ResourceManager.GetString("DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraný soubor neobsahuje uložené hodnoty nebo je poškozený..
        /// </summary>
        internal static string DataSetNotValid {
            get {
                return ResourceManager.GetString("DataSetNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vypnuto.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ve výrazu se může vyskytovat pouze jedna proměnná.
        /// </summary>
        internal static string DistinctVariableCountExceeded {
            get {
                return ResourceManager.GetString("DistinctVariableCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dynamicky.
        /// </summary>
        internal static string Dynamic {
            get {
                return ResourceManager.GetString("Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadejte aritmetický výraz….
        /// </summary>
        internal static string EnterArithmeticExpression {
            get {
                return ResourceManager.GetString("EnterArithmeticExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chyba.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uložení tohoto intervalu pravděpodobně zabere velké množství místa.
        ///
        ///Počet hodnot v intervalu: {0}
        ///Odhadovaná velikost souboru: {1}
        ///
        ///Opravdu si přejete uložit zvolený interval funkce do souboru?.
        /// </summary>
        internal static string FileTooBigToSave {
            get {
                return ResourceManager.GetString("FileTooBigToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet hodnot v intervalu: {0}
        ///Nalezení rozdílů v tomto intervalu pravděpodobně bude trvat:
        ///{1}
        ///
        ///Opravdu si přejete prohledat zadaný interval?.
        /// </summary>
        internal static string FindDifferencesIntervalTooBig {
            get {
                return ResourceManager.GetString("FindDifferencesIntervalTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nelze vyhledat rozdíly v intervalu procházející nulou.
        ///Obsahuje příliš mnoho hodnot..
        /// </summary>
        internal static string FindDifferencesIntervalWithZero {
            get {
                return ResourceManager.GetString("FindDifferencesIntervalWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chyba při stanovování intervalu pro vyhledávání..
        /// </summary>
        internal static string FindDifferencesInvalidInterval {
            get {
                return ResourceManager.GetString("FindDifferencesInvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Odhadovaný čas: {0} | Počet hodnot: {1}.
        /// </summary>
        internal static string FindDifferencesStatus {
            get {
                return ResourceManager.GetString("FindDifferencesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vyhledávání rozdílů.
        /// </summary>
        internal static string FindingDifferences {
            get {
                return ResourceManager.GetString("FindingDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Prohledávání dokončeno.
        /// </summary>
        internal static string FindingDifferencesComplete {
            get {
                return ResourceManager.GetString("FindingDifferencesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Prohledávání bylo dokončeno.
        ///
        ///Počet hodnot v intervalu: {0}
        ///Počet nalezených rozdílů: {1} ({2} %).
        /// </summary>
        internal static string FindingDifferencesCompleteDescription {
            get {
                return ResourceManager.GetString("FindingDifferencesCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vyhledávání rozdílů.
        /// </summary>
        internal static string FindingDifferencesDescription {
            get {
                return ResourceManager.GetString("FindingDifferencesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet zpracovaných hodnot: {0} / {1}.
        /// </summary>
        internal static string FindingDifferencesProgress {
            get {
                return ResourceManager.GetString("FindingDifferencesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet rozdílů v mezipaměti: {0} / {1}.
        /// </summary>
        internal static string GraphCachedDifferences {
            get {
                return ResourceManager.GetString("GraphCachedDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Okamžitě.
        /// </summary>
        internal static string Immediately {
            get {
                return ResourceManager.GetString("Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnotu konce intervalu nelze převést na číslo.
        ///Zkontrolujte, že číslo neobsahuje mezery a je použita desetinná tečka..
        /// </summary>
        internal static string IntervalEndInvalid {
            get {
                return ResourceManager.GetString("IntervalEndInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnotu začátku intervalu nelze převést na číslo.
        ///Zkontrolujte, že číslo neobsahuje mezery a je použita desetinná tečka..
        /// </summary>
        internal static string IntervalStartInvalid {
            get {
                return ResourceManager.GetString("IntervalStartInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Číslo nelze zpracovat.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Knihovna.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Seznam je prázdný.
        /// </summary>
        internal static string ListIsEmpty {
            get {
                return ResourceManager.GetString("ListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Otevřít soubor hodnot....
        /// </summary>
        internal static string LoadDataSet {
            get {
                return ResourceManager.GetString("LoadDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Otevřít knihovnu s matematickými funkcemi....
        /// </summary>
        internal static string LoadMathLibrary {
            get {
                return ResourceManager.GetString("LoadMathLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rozhraní .NET.
        /// </summary>
        internal static string MathLibraryInternal {
            get {
                return ResourceManager.GetString("MathLibraryInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraná knihovna neobsahuje matematické funkce..
        /// </summary>
        internal static string MathLibraryNotValid {
            get {
                return ResourceManager.GetString("MathLibraryNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraná knihovna byla pravděpodobně sestavena pro jiný typ procesoru než x86..
        /// </summary>
        internal static string MathLibraryPlatformMismatch {
            get {
                return ResourceManager.GetString("MathLibraryPlatformMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chybějící funkce: .
        /// </summary>
        internal static string MissingCallbacks {
            get {
                return ResourceManager.GetString("MissingCallbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Více než 1000 let.
        /// </summary>
        internal static string MoreThan1000Years {
            get {
                return ResourceManager.GetString("MoreThan1000Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pouze rozdíly.
        /// </summary>
        internal static string OnlyDifferences {
            get {
                return ResourceManager.GetString("OnlyDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chybný počet závorek.
        /// </summary>
        internal static string ParenthesesCountMismatch {
            get {
                return ResourceManager.GetString("ParenthesesCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Část funkce.
        /// </summary>
        internal static string PartOfFunction {
            get {
                return ResourceManager.GetString("PartOfFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Obyčejně.
        /// </summary>
        internal static string Plain {
            get {
                return ResourceManager.GetString("Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zbývá přibližně {0}..
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uložit soubor hodnot....
        /// </summary>
        internal static string SaveDataSet {
            get {
                return ResourceManager.GetString("SaveDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Interval je pro uložení příliš velký..
        /// </summary>
        internal static string SaveDataSetIntervalTooBig {
            get {
                return ResourceManager.GetString("SaveDataSetIntervalTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nelze uložit interval čísel procházející nulou.
        ///Obsahoval by příliš mnoho hodnot..
        /// </summary>
        internal static string SaveDataSetIntervalWithZero {
            get {
                return ResourceManager.GetString("SaveDataSetIntervalWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tento druh položky není podporován. Je možné uložit pouze hodnoty aritmetického výrazu..
        /// </summary>
        internal static string SaveDataSetUnsupportedItem {
            get {
                return ResourceManager.GetString("SaveDataSetUnsupportedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ukládání hodnot.
        /// </summary>
        internal static string SavingDataSet {
            get {
                return ResourceManager.GetString("SavingDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ukládání hodnot do souboru.
        /// </summary>
        internal static string SavingDataSetDescription {
            get {
                return ResourceManager.GetString("SavingDataSetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet uložených hodnot: {0} / {1}.
        /// </summary>
        internal static string SavingDataSetProgress {
            get {
                return ResourceManager.GetString("SavingDataSetProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} dní a {1} hodin.
        /// </summary>
        internal static string TimeDaysAndHours {
            get {
                return ResourceManager.GetString("TimeDaysAndHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} roky a {1} dní.
        /// </summary>
        internal static string TimeFewYearsAndDays {
            get {
                return ResourceManager.GetString("TimeFewYearsAndDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} hodin a {1} minut.
        /// </summary>
        internal static string TimeHoursAndMinutes {
            get {
                return ResourceManager.GetString("TimeHoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} minut a {1} sekund.
        /// </summary>
        internal static string TimeMinutesAndSeconds {
            get {
                return ResourceManager.GetString("TimeMinutesAndSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1 rok a {0} dní.
        /// </summary>
        internal static string TimeOneYearAndDays {
            get {
                return ResourceManager.GetString("TimeOneYearAndDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} sekund.
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} let a {1} dní.
        /// </summary>
        internal static string TimeYearsAndDays {
            get {
                return ResourceManager.GetString("TimeYearsAndDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Varování.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný x86 Remoting.
        /// </summary>
        internal static string X86Remoting {
            get {
                return ResourceManager.GetString("X86Remoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
